# 设置编译器：优先使用 Clang
if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(STATUS "Using Clang as the compiler")
else()
    if (WIN32)
        set(CMAKE_C_COMPILER "clang")
        set(CMAKE_CXX_COMPILER "clang++")
    elseif (UNIX)
        find_program(CLANG_PATH clang++)
        if (CLANG_PATH)
            set(CMAKE_CXX_COMPILER ${CLANG_PATH})
            message(STATUS "Found clang++ at ${CLANG_PATH}")
        else()
            message(FATAL_ERROR "clang++ not found!")
        endif()
    endif()
endif()

# 设置 Ninja 作为构建工具
if (CMAKE_GENERATOR STREQUAL "")
    set(CMAKE_GENERATOR "Ninja" CACHE STRING "" FORCE)
endif()

# 平台特定编译选项
if (WIN32)
    message(STATUS "Configuring for Windows")
    add_compile_options(-Wall -Wextra -Wpedantic)
    add_compile_definitions(WINDOWS_BUILD)
elseif (UNIX)
    message(STATUS "Configuring for Ubuntu/Linux")
    add_compile_options(-Wall -Wextra -Wpedantic -pthread)
    add_compile_definitions(UNIX_BUILD)
else()
    message(FATAL_ERROR "Unsupported platform!")
endif()